# Run with visual studio code 'REST Client' extension


GET http://localhost:8080/status HTTP/1.1

###

GET http://localhost:8080/votes HTTP/1.1

###

POST http://localhost:8080/vote/cats HTTP/1.1

###

POST http://localhost:8080/vote/dogs HTTP/1.1
